### ISSUE TITLE
EPG Importer 

### ISSUE THREAD

**Issue by kiddac** [OpenPLi/enigma2-plugin-extensions-epgimport#15]
Well done once again in totally breaking everything just like you did with the button code changes
So every plugin, script & provider of IPTV epgs now have to change all their code because of this totally unnecessary change. 
Don't you guys ever check anything outside your own little bubble. 
Bravo once again.

**Comment by WanWizard** [comment]
Do you really think writing three different comments, without ANY detail about what is wrong, and why, helps? 

If you have something useful to contribute, by all means, do so. If not, STFU.
