### ISSUE TITLE
EPGImport not working

### ISSUE THREAD

**Issue by maxbambi** [OpenPLi/enigma2-plugin-extensions-epgimport#18]
There are few days that I have noticed that decoder in on in the morning ( I have set epgimport at 5 o'clock in the night) 
Trying manual epg update, I got an error...
First "EPG import was yet active" ( probably from the night!)
Then I rebooted and EPG tried to start but "Name or service not known"
I would like to reinstall plugin, but last installation is without sources xml file

**Comment by pr2git** [comment]
Which image are you using? I guess that it is not OpenPLi so you are using XMLTVImport.
That you can find here:

https://github.com/oe-alliance/XMLTV-Import

Setting the update at 5 o'clock is  bad idea since you are updating the EPG while the new files are uploaded to the server.

**Comment by WanWizard** [comment]
Depends on the timezone. ;-)

In general downloads should happen after 7:30 CET/CEST.

**Comment by pr2git** [comment]
source are part of a dedicated package, if you install the source it will install the importer because there is a dependencies but not the other way. So if you install just the imported then install also the source from the feed.

**Comment by maxbambi** [comment]
I'm using Openatv on Octagon sf4008... 
In the link you have told me, an issue has been just opened about my error
[https://github.com/oe-alliance/XMLTV-Import/issues/30](url)

You can close this issue...
