### ISSUE TITLE
Channels will not be assigned

### ISSUE THREAD

**Issue by DocUltra** [OpenPLi/enigma2-plugin-extensions-epgimport#20]
Hi,

I installed OpenPLI 6.2 and have the problem, so that the plugin don´t assign the channels?

pls. see the log

f not in bouquets: 1:0:19:DAD:23:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:10D8:2B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:B55:1D:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:57D:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:709:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:DAE:23:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:DAE:23:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70B:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:D4B:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:D4B:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70A:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:A2A:1A:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:A2A:1A:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70C:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:C83:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:C83:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70D:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:D4A:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70E:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:C82:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:C82:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:713:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:A2B:1A:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:A2B:1A:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:712:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:10D0:2B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:9C7:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:70F:12:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:BBB:1E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:BBB:1E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:CE:2:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:1005:29:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:A91:1B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:329:8:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:8FF:17:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:2C9:7:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:2C2:7:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:D49:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:D49:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:519:D:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:7DF:14:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:1006:29:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:A92:1B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:393:9:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:DAF:23:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:269:6:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:518:D:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:903:17:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:C81:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:C81:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:2C3:7:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:8FD:17:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:585:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:961:18:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:19E:4:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:9C5:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:9C5:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:57B:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:FA5:28:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:FA5:28:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:57C:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:83B:15:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:DB3:23:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:201:5:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:967:18:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:203:5:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:C87:20:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:D4F:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:32D:8:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4BC:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4BF:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4B9:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:321:8:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:580:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:AF4:1C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:AF4:1C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4BE:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:9D0:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:6AC:11:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:280A:66:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:586:E:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:6AB:11:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:5DF:F:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:458:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:133:3:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:D4E:22:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:E78:25:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:1FD:5:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:202:5:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:96B:18:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:459:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:9CC:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:45A:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:3F2:A:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:83D:15:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:267:6:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:38B:9:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:8FE:17:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:8FE:17:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:38D:9:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:197:4:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:9CF:19:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:199:4:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:CE8:21:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:D1:2:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4B8:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:CF:2:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:4BB:C:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:456:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:19:B5B:1D:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:455:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:452:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:5EA:F:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:453:B:F020:FFFF0000:0:0:0:
Serviceref not in bouquets: 1:0:1:9C7:19:F020:FFFF0000:0:0:0:
[XMLTVConverter] Enumerating event information
Unknown channel:  canalalphane.ch
Unknown channel:  canalalphaju.ch
Unknown channel:  rtl9.ch
Unknown channel:  w9.ch
Unknown channel:  switzerland5.ch
Unknown channel:  telezuri.ch
Unknown channel:  3plus.ch
Unknown channel:  4plus.ch
Unknown channel:  5plus.ch
Unknown channel:  mtv.ch
Unknown channel:  puls8.ch
Unknown channel:  s1.ch
Unknown channel:  startv.ch
Unknown channel:  tccinema.ch
Unknown channel:  tcstar.ch
Unknown channel:  telem1.ch
Unknown channel:  tvo.ch
Unknown channel:  tv24.ch
Unknown channel:  comedyviva.ch
Unknown channel:  tv25.ch
Unknown channel:  swiss1.ch
[EPGImport] ### thread is ready ### Events: 2487
[EPGImport] imported 2487 events
[EPGImport] Save last import date and count event18:F020:FFFF0000:0:0:0::0:0:0:
[EPGImport] Run check deep standby after import
[EPGImport] #### Finished ####
[EPGImport] WakeUpTime now set to -1 (now=1541856208)

**Comment by WanWizard** [comment]
For enduser support, please go to https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/
