### ISSUE TITLE
Turkish language add please

### ISSUE THREAD

**Issue by docea37** [OpenPLi/enigma2-plugin-extensions-epgimport#22]
hi
Turkish language add please
[EPGImport.zip](https://github.com/OpenPLi/enigma2-plugin-extensions-epgimport/files/2813696/EPGImport.zip)

**Comment by WanWizard** [comment]
That requires command of the language.

You can have a go yourself, see https://wiki.openpli.org/Information_for_translators for information on how to do it. There is also topic on the forum to support translators.
