### ISSUE TITLE
openpli 7.0 epg is not downloading

### ISSUE THREAD

**Issue by docea37** [OpenPLi/enigma2-plugin-extensions-epgimport#23]
Vu+ zero 4K -  openpli-7.0-release-vuzero4k-20190128_usb.zip
epgimport-rytec(20180913-r0.0)

```
<sourcecat sourcecatname="Turkish XMLTV">	
<source type="gen_xmltv" channels="http://www.cccambrowser.eu5.org/epg/digiturk.channels.xml.xz">
<description>DigiTurk XMLTV (By Docea37)</description>
<url>http://www.cccambrowser.eu5.org/epg/epg.xml.gz</url>
 </source>
</sourcecat>
```

epg is not downloading

tried file extensions
epg.xml.xz
epg.xml.gz
 epg.xml

**Comment by WanWizard** [comment]
For EPG import questions, please go to the Rytec forum: https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/.
