### ISSUE TITLE
EPG data missing for some channels

### ISSUE THREAD

**Issue by joniale** [OpenPLi/enigma2-plugin-extensions-epgimport#25]
Hi EPG importer developers,
I have seen in other thread related to IPTV 2 bouquet plugin an error report for EPG importer see
su1s/e2m3u2bouquet#37

The thing is that i am experience the same problem. I see that some channels that do not have a description are not shown in the EPG information.
Could you check and correct this behavior?
Some EPG providers only describe the tittle and start and end of program for one channels and for others they put more information as the the "desc"/description but it should not be mandatory.

Best regards,
Jonathan

**Comment by WanWizard** [comment]
There is nothing in the code that would skip an entry based on a missing description. 

As far as I can see, there are only three mandatory fields, start, stop, and the service must exist (= the channel to service ref mapping must exist, and the service ref must exist in your channel list).

There is no active support for this plugin on Github, the XMLTV guys have a support forum here: https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/

**Comment by joniale** [comment]
I think it was something related with the image of OpenVix i updated to the new one which have the newest epg importer version and the  problem is gone

**Comment by WanWizard** [comment]
No clue, we don't "do" OpenVIX. ;)
