### ISSUE TITLE
import don't work

### ISSUE THREAD

**Issue by McPaHa** [OpenPLi/enigma2-plugin-extensions-epgimport#38]
Hi!

I am using epg import with VTi 14.0.5 (Duo2).

Reason I do not know epgimport plugin log shows me an error:

`root@vuduo2:/tmp# more epgimport.log
[EPGImport] autostart (0) occured at 1580415399.0
[EPGImport] autostart (0) occured at 1580415399.25
[EPGImport] WakeUpTime now set to 1580454350 (now=1580415399)
[EPGImport] nextImport, source= Rytec-Suomi-Yhteinen
[EPGImport] Downloading: http://www.xmltvepg.nl/rytecFI_Misc.xz to local path: /tmp/epgimport.xz
[EPGImport] afterDownload /tmp/epgimport.xz
[EPGImport] unlink /tmp/epgimport.xz
[EPGImport] afterChannelDownload None
[EPGImport] Parsing channels from '/etc/epgimport/jex.epg.channels.xml'
[XMLTVConverter] Enumerating event information
[EPGImport] nextImport, source= Rytec-UK-Ireland-Sky-1-(Live-on-sat)
[EPGImport] Downloading: http://www.xmltvepg.nl/rytecUK_SkyLive.xz to local path: /tmp/epgimport.xz
[EPGImport] connectionLost [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionFdescWentAway'>: Uh: Filedescriptor went away.
]
[EPGImport] afterDownload /tmp/epgimport.xz
[EPGImport] unlink /tmp/epgimport.xz
[EPGImport] afterChannelDownload None
[XMLTVConverter] Enumerating event information
[EPGImport] nextImport, source= Rytec-UK-Ireland-FTA
[EPGImport] Downloading: http://www.xmltvepg.nl/rytecUK_FTA.xz to local path: /tmp/epgimport.xz
[EPGImport] connectionLost [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionFdescWentAway'>: Uh: Filedescriptor went away.`

At the same time connection manually working:

`root@vuduo2:/tmp# wget http://www.xmltvepg.nl/rytecUK_FTA.xz
Connecting to www.xmltvepg.nl (51.15.49.64:80)
rytecUK_FTA.xz       100% |**************************************************************************************************************|   284k  0:00:00 ETA
root@vuduo2:/tmp#
`

**Comment by WanWizard** [comment]
twisted.internet.error.ConnectionFdescWentAway means connection lost. 

Shouldn't be a problem, the plugin should retry with another downlod mirror (assuming VTi uses an up to date version of the plugin and multiple download sources).

**Comment by McPaHa** [comment]
epg is empty and downloaded 0.

**Comment by WanWizard** [comment]
I can't really comment on what VTi has put in the image, and how it is configured.

I suggest you report it in the EPG support forum: https://forums.openpli.org/forum/52-en-rytec-xmltv-and-epg-support/

**Comment by pr2git** [comment]
You should create your issue report here:
https://github.com/oe-alliance/XMLTV-Import

Since OE-Alliance image are not using this repository but the one I mention. The log is disturbing because this still report EPGimport but it's not.
The way the files are downloaded is different between both plugin.

This issue should be closed I think.
